//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionImage
    {
        public int Id_QuestionImage { get; set; }
        public int Question_id { get; set; }
        public byte[] QuestionImageSrc { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
